---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-controller
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkins-controller
      nodePort: 30088
    - port: 30500
      targetPort: 30500
      name: jenkins-jnlp
      nodePort: 30500
  selector:
    app: jenkins-controller
